// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: url.proto

package url

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	user "url-service/pb/user"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Redirect string     `protobuf:"bytes,2,opt,name=redirect,proto3" json:"redirect,omitempty"`
	TVF      string     `protobuf:"bytes,3,opt,name=TVF,proto3" json:"TVF,omitempty"`
	Random   bool       `protobuf:"varint,4,opt,name=random,proto3" json:"random,omitempty"`
	Owner    *user.User `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *URL) Reset() {
	*x = URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *URL) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *URL) GetTVF() string {
	if x != nil {
		return x.TVF
	}
	return ""
}

func (x *URL) GetRandom() bool {
	if x != nil {
		return x.Random
	}
	return false
}

func (x *URL) GetOwner() *user.User {
	if x != nil {
		return x.Owner
	}
	return nil
}

type CreateUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Redirect string `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	TVF      string `protobuf:"bytes,2,opt,name=TVF,proto3" json:"TVF,omitempty"`
	Random   bool   `protobuf:"varint,3,opt,name=random,proto3" json:"random,omitempty"`
}

func (x *CreateUrlReq) Reset() {
	*x = CreateUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlReq) ProtoMessage() {}

func (x *CreateUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlReq.ProtoReflect.Descriptor instead.
func (*CreateUrlReq) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUrlReq) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *CreateUrlReq) GetTVF() string {
	if x != nil {
		return x.TVF
	}
	return ""
}

func (x *CreateUrlReq) GetRandom() bool {
	if x != nil {
		return x.Random
	}
	return false
}

type CreateUrlRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Redirect string `protobuf:"bytes,2,opt,name=redirect,proto3" json:"redirect,omitempty"`
	TVF      string `protobuf:"bytes,3,opt,name=TVF,proto3" json:"TVF,omitempty"`
	Random   bool   `protobuf:"varint,4,opt,name=random,proto3" json:"random,omitempty"`
}

func (x *CreateUrlRes) Reset() {
	*x = CreateUrlRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlRes) ProtoMessage() {}

func (x *CreateUrlRes) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlRes.ProtoReflect.Descriptor instead.
func (*CreateUrlRes) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUrlRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUrlRes) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *CreateUrlRes) GetTVF() string {
	if x != nil {
		return x.TVF
	}
	return ""
}

func (x *CreateUrlRes) GetRandom() bool {
	if x != nil {
		return x.Random
	}
	return false
}

type GetRedirectByTVFReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TVF string `protobuf:"bytes,1,opt,name=TVF,proto3" json:"TVF,omitempty"`
}

func (x *GetRedirectByTVFReq) Reset() {
	*x = GetRedirectByTVFReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRedirectByTVFReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedirectByTVFReq) ProtoMessage() {}

func (x *GetRedirectByTVFReq) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedirectByTVFReq.ProtoReflect.Descriptor instead.
func (*GetRedirectByTVFReq) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{3}
}

func (x *GetRedirectByTVFReq) GetTVF() string {
	if x != nil {
		return x.TVF
	}
	return ""
}

type GetRedirectByTVFRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Redirect string `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
}

func (x *GetRedirectByTVFRes) Reset() {
	*x = GetRedirectByTVFRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRedirectByTVFRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedirectByTVFRes) ProtoMessage() {}

func (x *GetRedirectByTVFRes) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedirectByTVFRes.ProtoReflect.Descriptor instead.
func (*GetRedirectByTVFRes) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{4}
}

func (x *GetRedirectByTVFRes) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

type GetURLsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetURLsReq) Reset() {
	*x = GetURLsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsReq) ProtoMessage() {}

func (x *GetURLsReq) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsReq.ProtoReflect.Descriptor instead.
func (*GetURLsReq) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{5}
}

type GetURLsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*URL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *GetURLsRes) Reset() {
	*x = GetURLsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsRes) ProtoMessage() {}

func (x *GetURLsRes) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsRes.ProtoReflect.Descriptor instead.
func (*GetURLsRes) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{6}
}

func (x *GetURLsRes) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUrlReq) Reset() {
	*x = DeleteUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlReq) ProtoMessage() {}

func (x *DeleteUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlReq.ProtoReflect.Descriptor instead.
func (*DeleteUrlReq) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUrlReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUrlRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUrlRes) Reset() {
	*x = DeleteUrlRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUrlRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlRes) ProtoMessage() {}

func (x *DeleteUrlRes) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlRes.ProtoReflect.Descriptor instead.
func (*DeleteUrlRes) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{8}
}

type GetURLsByOwnerIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *GetURLsByOwnerIDReq) Reset() {
	*x = GetURLsByOwnerIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsByOwnerIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsByOwnerIDReq) ProtoMessage() {}

func (x *GetURLsByOwnerIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsByOwnerIDReq.ProtoReflect.Descriptor instead.
func (*GetURLsByOwnerIDReq) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{9}
}

func (x *GetURLsByOwnerIDReq) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetURLsByOwnerIDRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*URL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *GetURLsByOwnerIDRes) Reset() {
	*x = GetURLsByOwnerIDRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLsByOwnerIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsByOwnerIDRes) ProtoMessage() {}

func (x *GetURLsByOwnerIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsByOwnerIDRes.ProtoReflect.Descriptor instead.
func (*GetURLsByOwnerIDRes) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{10}
}

func (x *GetURLsByOwnerIDRes) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_url_proto protoreflect.FileDescriptor

var file_url_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x03, 0x55,
	0x52, 0x4c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x54, 0x56, 0x46, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x56, 0x46,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x56, 0x46, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x54, 0x56, 0x46, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x64,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x56,
	0x46, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x56, 0x46, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x42, 0x79, 0x54, 0x56, 0x46, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x54,
	0x56, 0x46, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x56, 0x46, 0x22, 0x31, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x42, 0x79, 0x54, 0x56,
	0x46, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x22, 0x29,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x52, 0x4c, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x32,
	0xa5, 0x02, 0x0a, 0x0a, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x12,
	0x2f, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x6c, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c,
	0x73, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c,
	0x73, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x73, 0x12, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x42, 0x79, 0x54, 0x56, 0x46, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x42, 0x79, 0x54, 0x56, 0x46, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x42,
	0x79, 0x54, 0x56, 0x46, 0x52, 0x65, 0x73, 0x42, 0x14, 0x5a, 0x12, 0x75, 0x72, 0x6c, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x72, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_url_proto_rawDescOnce sync.Once
	file_url_proto_rawDescData = file_url_proto_rawDesc
)

func file_url_proto_rawDescGZIP() []byte {
	file_url_proto_rawDescOnce.Do(func() {
		file_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_url_proto_rawDescData)
	})
	return file_url_proto_rawDescData
}

var file_url_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_url_proto_goTypes = []interface{}{
	(*URL)(nil),                 // 0: pb.URL
	(*CreateUrlReq)(nil),        // 1: pb.CreateUrlReq
	(*CreateUrlRes)(nil),        // 2: pb.CreateUrlRes
	(*GetRedirectByTVFReq)(nil), // 3: pb.GetRedirectByTVFReq
	(*GetRedirectByTVFRes)(nil), // 4: pb.GetRedirectByTVFRes
	(*GetURLsReq)(nil),          // 5: pb.GetURLsReq
	(*GetURLsRes)(nil),          // 6: pb.GetURLsRes
	(*DeleteUrlReq)(nil),        // 7: pb.DeleteUrlReq
	(*DeleteUrlRes)(nil),        // 8: pb.DeleteUrlRes
	(*GetURLsByOwnerIDReq)(nil), // 9: pb.GetURLsByOwnerIDReq
	(*GetURLsByOwnerIDRes)(nil), // 10: pb.GetURLsByOwnerIDRes
	(*user.User)(nil),           // 11: pb.User
}
var file_url_proto_depIdxs = []int32{
	11, // 0: pb.URL.owner:type_name -> pb.User
	0,  // 1: pb.GetURLsRes.urls:type_name -> pb.URL
	0,  // 2: pb.GetURLsByOwnerIDRes.urls:type_name -> pb.URL
	1,  // 3: pb.URLService.CreateUrl:input_type -> pb.CreateUrlReq
	7,  // 4: pb.URLService.DeleteURl:input_type -> pb.DeleteUrlReq
	9,  // 5: pb.URLService.GetURLsByOwnerID:input_type -> pb.GetURLsByOwnerIDReq
	5,  // 6: pb.URLService.GetURLs:input_type -> pb.GetURLsReq
	3,  // 7: pb.URLService.GetRedirectByTVF:input_type -> pb.GetRedirectByTVFReq
	2,  // 8: pb.URLService.CreateUrl:output_type -> pb.CreateUrlRes
	8,  // 9: pb.URLService.DeleteURl:output_type -> pb.DeleteUrlRes
	9,  // 10: pb.URLService.GetURLsByOwnerID:output_type -> pb.GetURLsByOwnerIDReq
	6,  // 11: pb.URLService.GetURLs:output_type -> pb.GetURLsRes
	4,  // 12: pb.URLService.GetRedirectByTVF:output_type -> pb.GetRedirectByTVFRes
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_url_proto_init() }
func file_url_proto_init() {
	if File_url_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRedirectByTVFReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRedirectByTVFRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUrlRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLsByOwnerIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLsByOwnerIDRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_url_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_proto_goTypes,
		DependencyIndexes: file_url_proto_depIdxs,
		MessageInfos:      file_url_proto_msgTypes,
	}.Build()
	File_url_proto = out.File
	file_url_proto_rawDesc = nil
	file_url_proto_goTypes = nil
	file_url_proto_depIdxs = nil
}
