// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: url.proto

package url

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// URLServiceClient is the client API for URLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLServiceClient interface {
	// URL RPC
	CreateUrl(ctx context.Context, in *CreateUrlReq, opts ...grpc.CallOption) (*CreateUrlRes, error)
	DeleteURl(ctx context.Context, in *DeleteUrlReq, opts ...grpc.CallOption) (*DeleteUrlRes, error)
	GetURLsByOwnerID(ctx context.Context, in *GetURLsByOwnerIDReq, opts ...grpc.CallOption) (*GetURLsByOwnerIDReq, error)
	GetURLs(ctx context.Context, in *GetURLsReq, opts ...grpc.CallOption) (*GetURLsRes, error)
	GetRedirectByTVF(ctx context.Context, in *GetRedirectByTVFReq, opts ...grpc.CallOption) (*GetRedirectByTVFRes, error)
}

type uRLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewURLServiceClient(cc grpc.ClientConnInterface) URLServiceClient {
	return &uRLServiceClient{cc}
}

func (c *uRLServiceClient) CreateUrl(ctx context.Context, in *CreateUrlReq, opts ...grpc.CallOption) (*CreateUrlRes, error) {
	out := new(CreateUrlRes)
	err := c.cc.Invoke(ctx, "/pb.URLService/CreateUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLServiceClient) DeleteURl(ctx context.Context, in *DeleteUrlReq, opts ...grpc.CallOption) (*DeleteUrlRes, error) {
	out := new(DeleteUrlRes)
	err := c.cc.Invoke(ctx, "/pb.URLService/DeleteURl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLServiceClient) GetURLsByOwnerID(ctx context.Context, in *GetURLsByOwnerIDReq, opts ...grpc.CallOption) (*GetURLsByOwnerIDReq, error) {
	out := new(GetURLsByOwnerIDReq)
	err := c.cc.Invoke(ctx, "/pb.URLService/GetURLsByOwnerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLServiceClient) GetURLs(ctx context.Context, in *GetURLsReq, opts ...grpc.CallOption) (*GetURLsRes, error) {
	out := new(GetURLsRes)
	err := c.cc.Invoke(ctx, "/pb.URLService/GetURLs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLServiceClient) GetRedirectByTVF(ctx context.Context, in *GetRedirectByTVFReq, opts ...grpc.CallOption) (*GetRedirectByTVFRes, error) {
	out := new(GetRedirectByTVFRes)
	err := c.cc.Invoke(ctx, "/pb.URLService/GetRedirectByTVF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLServiceServer is the server API for URLService service.
// All implementations must embed UnimplementedURLServiceServer
// for forward compatibility
type URLServiceServer interface {
	// URL RPC
	CreateUrl(context.Context, *CreateUrlReq) (*CreateUrlRes, error)
	DeleteURl(context.Context, *DeleteUrlReq) (*DeleteUrlRes, error)
	GetURLsByOwnerID(context.Context, *GetURLsByOwnerIDReq) (*GetURLsByOwnerIDReq, error)
	GetURLs(context.Context, *GetURLsReq) (*GetURLsRes, error)
	GetRedirectByTVF(context.Context, *GetRedirectByTVFReq) (*GetRedirectByTVFRes, error)
	mustEmbedUnimplementedURLServiceServer()
}

// UnimplementedURLServiceServer must be embedded to have forward compatible implementations.
type UnimplementedURLServiceServer struct {
}

func (UnimplementedURLServiceServer) CreateUrl(context.Context, *CreateUrlReq) (*CreateUrlRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUrl not implemented")
}
func (UnimplementedURLServiceServer) DeleteURl(context.Context, *DeleteUrlReq) (*DeleteUrlRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteURl not implemented")
}
func (UnimplementedURLServiceServer) GetURLsByOwnerID(context.Context, *GetURLsByOwnerIDReq) (*GetURLsByOwnerIDReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetURLsByOwnerID not implemented")
}
func (UnimplementedURLServiceServer) GetURLs(context.Context, *GetURLsReq) (*GetURLsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetURLs not implemented")
}
func (UnimplementedURLServiceServer) GetRedirectByTVF(context.Context, *GetRedirectByTVFReq) (*GetRedirectByTVFRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedirectByTVF not implemented")
}
func (UnimplementedURLServiceServer) mustEmbedUnimplementedURLServiceServer() {}

// UnsafeURLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLServiceServer will
// result in compilation errors.
type UnsafeURLServiceServer interface {
	mustEmbedUnimplementedURLServiceServer()
}

func RegisterURLServiceServer(s grpc.ServiceRegistrar, srv URLServiceServer) {
	s.RegisterService(&URLService_ServiceDesc, srv)
}

func _URLService_CreateUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLServiceServer).CreateUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.URLService/CreateUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLServiceServer).CreateUrl(ctx, req.(*CreateUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLService_DeleteURl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLServiceServer).DeleteURl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.URLService/DeleteURl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLServiceServer).DeleteURl(ctx, req.(*DeleteUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLService_GetURLsByOwnerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetURLsByOwnerIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLServiceServer).GetURLsByOwnerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.URLService/GetURLsByOwnerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLServiceServer).GetURLsByOwnerID(ctx, req.(*GetURLsByOwnerIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLService_GetURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetURLsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLServiceServer).GetURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.URLService/GetURLs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLServiceServer).GetURLs(ctx, req.(*GetURLsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLService_GetRedirectByTVF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedirectByTVFReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLServiceServer).GetRedirectByTVF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.URLService/GetRedirectByTVF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLServiceServer).GetRedirectByTVF(ctx, req.(*GetRedirectByTVFReq))
	}
	return interceptor(ctx, in, info, handler)
}

// URLService_ServiceDesc is the grpc.ServiceDesc for URLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.URLService",
	HandlerType: (*URLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUrl",
			Handler:    _URLService_CreateUrl_Handler,
		},
		{
			MethodName: "DeleteURl",
			Handler:    _URLService_DeleteURl_Handler,
		},
		{
			MethodName: "GetURLsByOwnerID",
			Handler:    _URLService_GetURLsByOwnerID_Handler,
		},
		{
			MethodName: "GetURLs",
			Handler:    _URLService_GetURLs_Handler,
		},
		{
			MethodName: "GetRedirectByTVF",
			Handler:    _URLService_GetRedirectByTVF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url.proto",
}
